name: Build and Deploy
on:
  pull_request:
    branches:
      - main 
  push:
    branches:
      - main 
env:
  APP_NAME: github-runner
  VERSION: '${{ vars.VERSION }}.${{ github.run_number }}.${{ github.run_attempt }}'
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }} 
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }} 
  AZURE_GROUP_KUBERNETES: ${{ vars.AZURE_RESOURCE_GROUP_KUBERNETES }} 
  AZURE_GROUP_DELIVERY: ${{ vars.AZURE_RESOURCE_GROUP_DELIVERY }} 
  AZURE_SUBSCRIPTION_ID: ${{ github.ref == 'refs/heads/main' && secrets.PRODUCTION_AZURE_SUBSCRIPTION_ID || secrets.STAGING_AZURE_SUBSCRIPTION_ID }}
  GITHUB_RUNNER_CONTAINER_IMAGE: ghcr.io/nano-core/nano-github-runner
  GITHUB_RUNNER_CONTAINER_IMAGE_TAG: latest
  GITHUB_RUNNER_OWNER: ${{ github.repository_owner }}
  GITHUB_RUNNER_APP_ID: ${{ secrets.GITHUBRUNNER_APP_ID }}
  GITHUB_RUNNER_INSTALLATION_ID: ${{ secrets.GITHUBRUNNER_INSTALLATION_ID }}
  GITHUB_RUNNER_PRIVATE_KEY: ${{ secrets.GITHUBRUNNER_PRIVATE_KEY }}
  GITHUB_RUNNER_ENV_LABEL: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Staging' }}
  GITHUB_RUNNER_REPLICA_TIMEOUT: 600
  GITHUB_RUNNER_REPLICA_RETRY_LIMIT: 1
  GITHUB_RUNNER_MIN_EXECUTIONS: 0
  GITHUB_RUNNER_MAX_EXECUTIONS: 10
  GITHUB_RUNNER_CPU: 2
  GITHUB_RUNNER_MEMORY: 4Gi
  GITHUB_RUNNER_POLLING_INTERVAL: 30
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.repository }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v6

      - name: Azure Login
        shell: pwsh
        run: |
          az login --service-principal -u $env:AZURE_CLIENT_ID -p $env:AZURE_CLIENT_SECRET --tenant $env:AZURE_TENANT_ID -o none;
          az account set -s $env:AZURE_SUBSCRIPTION_ID -o none;

          $env:KUBERNETES_CLUSTER = az aks list -g $env:AZURE_GROUP_KUBERNETES --query [0].name -o tsv;
          az aks get-credentials -g $env:AZURE_GROUP_KUBERNETES -n $env:KUBERNETES_CLUSTER -o none;

      - name: Deploy GitHub Self-Hosted Runner
        shell: pwsh
        run: |
          $JobExists = az containerapp job list -g $env:AZURE_GROUP_DELIVERY --query "[?name=='$env:APP_NAME'].name" -o tsv;

          if (-not $JobExists) 
          {
              $env:GITHUB_RUNNER_ENVIRONMENT_NAME = az containerapp env list -g $env:AZURE_GROUP_DELIVERY --query [0].name -o tsv;

              az containerapp job create `
                  -n $env:APP_NAME `
                  -g $env:AZURE_GROUP_DELIVERY `
                  --trigger-type Event `
                  --environment $env:GITHUB_RUNNER_ENVIRONMENT_NAME `
                  --image "${env:GITHUB_RUNNER_CONTAINER_IMAGE}:${env:GITHUB_RUNNER_CONTAINER_IMAGE_TAG}" `
                  --replica-timeout $env:GITHUB_RUNNER_REPLICA_TIMEOUT `
                  --replica-retry-limit $env:GITHUB_RUNNER_REPLICA_RETRY_LIMIT `
                  --min-executions $env:GITHUB_RUNNER_MIN_EXECUTIONS `
                  --max-executions $env:GITHUB_RUNNER_MAX_EXECUTIONS `
                  --scale-rule-name $env:APP_NAME-scaler `
                  --scale-rule-type github-runner `
                  --scale-rule-metadata `
                      "owner=$env:GITHUB_RUNNER_OWNER" `
                      "runnerScope=org" `
                      "applicationID=$env:GITHUB_RUNNER_APP_ID" `
                      "installationID=$env:GITHUB_RUNNER_INSTALLATION_ID" `
                      "labels=$env:GITHUB_RUNNER_ENV_LABEL" `
                  --scale-rule-auth "appKey=github-app-key-secret" `
                  --cpu $env:GITHUB_RUNNER_CPU `
                  --memory $env:GITHUB_RUNNER_MEMORY `
                  --polling-interval $env:GITHUB_RUNNER_POLLING_INTERVAL `
                  --secrets "github-app-key-secret=$env:GITHUB_RUNNER_PRIVATE_KEY" `
                  --env-vars "APP_ID=$env:GITHUB_RUNNER_APP_ID" "APP_PRIVATE_KEY=secretref:github-app-key-secret" "APP_LOGIN=$env:GITHUB_RUNNER_OWNER" "RUNNER_SCOPE=org" "ORG_NAME=$env:GITHUB_RUNNER_OWNER" "RUN_AS_ROOT=false" "EPHEMERAL=true" "RUNNER_LABELS=$env:GITHUB_RUNNER_ENV_LABEL";
          } 
          else 
          {
              az containerapp job update `
                  -n $env:APP_NAME `
                  -g $env:AZURE_GROUP_DELIVERY `
                  --image "${env:GITHUB_RUNNER_CONTAINER_IMAGE}:${env:GITHUB_RUNNER_CONTAINER_IMAGE_TAG}" `
                  --replica-timeout $env:GITHUB_RUNNER_REPLICA_TIMEOUT `
                  --replica-retry-limit $env:GITHUB_RUNNER_REPLICA_RETRY_LIMIT `
                  --min-executions $env:GITHUB_RUNNER_MIN_EXECUTIONS `
                  --max-executions $env:GITHUB_RUNNER_MAX_EXECUTIONS `
                  --scale-rule-metadata `
                      "owner=$env:GITHUB_RUNNER_OWNER" `
                      "runnerScope=org" `
                      "applicationID=$env:GITHUB_RUNNER_APP_ID" `
                      "installationID=$env:GITHUB_RUNNER_INSTALLATION_ID" `
                      "labels=$env:GITHUB_RUNNER_ENV_LABEL" `
                  --scale-rule-auth "appKey=github-app-key-secret" `
                  --cpu $env:GITHUB_RUNNER_CPU `
                  --memory $env:GITHUB_RUNNER_MEMORY `
                  --polling-interval $env:GITHUB_RUNNER_POLLING_INTERVAL `
                  --set-env-vars "APP_ID=$env:GITHUB_RUNNER_APP_ID" "APP_PRIVATE_KEY=secretref:github-app-key-secret" "APP_LOGIN=$env:GITHUB_RUNNER_OWNER" "RUNNER_SCOPE=org" "ORG_NAME=$env:GITHUB_RUNNER_OWNER" "RUN_AS_ROOT=false" "EPHEMERAL=true" "RUNNER_LABELS=$env:GITHUB_RUNNER_ENV_LABEL";
          }

      - name: GitHub Release
        if: github.ref == 'refs/heads/main'
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: |
            Version: ${{ env.VERSION }}
            Commit: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false